# Generated by Django 4.2.2 on 2023-08-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalreg',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hospitalreg',
            name='licence',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
