# Generated by Django 4.2.2 on 2023-08-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0002_hospitalreg_image_hospitalreg_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreg',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medico_app.hospitalreg'),
        ),
        migrations.AddField(
            model_name='doctorreg',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='doctorreg',
            name='time_from',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctorreg',
            name='time_to',
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name='DoctorQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=30)),
                ('certificate', models.FileField(null=True, upload_to='')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico_app.doctorreg')),
            ],
        ),
    ]
