# Generated by Django 4.2.2 on 2023-08-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0003_doctorreg_hospital_doctorreg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreg',
            name='highest_quali',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doctorreg',
            name='quali_certi',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='DoctorQualification',
        ),
    ]
