# Generated by Django 4.2.2 on 2023-08-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0004_doctorreg_highest_quali_doctorreg_quali_certi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorreg',
            old_name='doctor_name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='doctorreg',
            name='lname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
