# Generated by Django 4.2.2 on 2023-08-25 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0005_rename_doctor_name_doctorreg_fname_doctorreg_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('patient_address', models.TextField()),
                ('gender', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30, null=True)),
                ('weight', models.CharField(max_length=30)),
                ('patient_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medico_app.doctorreg')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico_app.patientreg')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField()),
                ('app_time', models.TimeField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medico_app.doctorreg')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico_app.patientreg')),
            ],
        ),
    ]
