# Generated by Django 4.2.2 on 2023-08-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0006_patientreg_medical_history_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_time',
            field=models.CharField(max_length=30),
        ),
    ]
