# Generated by Django 4.2.2 on 2023-08-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0007_alter_appointment_app_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='app_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
