# Generated by Django 4.2.2 on 2023-08-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0008_appointment_app_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
