# Generated by Django 4.2.2 on 2023-08-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0009_appointment_booked_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreg',
            name='fee',
            field=models.CharField(default='200', max_length=30),
        ),
    ]
