# Generated by Django 4.2.2 on 2023-08-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0010_doctorreg_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paid_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='paytype',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
