# Generated by Django 4.2.2 on 2023-08-31 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0011_appointment_paid_on_appointment_paytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField()),
                ('next_app', models.DateField(blank=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medico_app.doctorreg')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico_app.patientreg')),
            ],
        ),
        migrations.CreateModel(
            name='Medicie_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=30)),
                ('m_dosage', models.CharField(max_length=30)),
                ('m_quantity', models.CharField(max_length=30)),
                ('m_directions', models.CharField(max_length=30)),
                ('m_days', models.CharField(max_length=30)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico_app.medical_record')),
            ],
        ),
        migrations.CreateModel(
            name='Test_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=30)),
                ('test_upload', models.FileField(blank=True, upload_to='')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico_app.medical_record')),
            ],
        ),
        migrations.DeleteModel(
            name='Medical_history',
        ),
    ]
