# Generated by Django 4.2.2 on 2023-08-31 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0012_medical_record_medicie_details_test_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_record',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medical_record',
            name='patient',
        ),
        migrations.AddField(
            model_name='medical_record',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medico_app.appointment'),
        ),
    ]
