# Generated by Django 4.2.2 on 2023-09-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0013_remove_medical_record_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='next_app',
            field=models.DateField(null=True),
        ),
    ]
