# Generated by Django 4.2.2 on 2023-09-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0014_alter_medical_record_next_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_record',
            name='symptoms',
            field=models.TextField(null=True),
        ),
    ]
